name: Publish Docker image
on:
  push:
    branches:
      - master
    tags:
      - "**"
jobs:
  push_to_registry:
    name: Push Docker image to Docker hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: What
        run: echo "RELEASE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            kape/github-transifex-action:${{ env.RELEASE_TAG }}
            kape/github-transifex-action:latest